import { FunctionDeclaration, Type } from "@google/genai";

export const toolDeclarations: FunctionDeclaration[] = [
    {
        name: "get_team_stats",
        description: "Get the win rate and performance metrics for a specific team.",
        parameters: {
            type: Type.OBJECT,
            properties: {
                teamName: {
                    type: Type.STRING,
                    description: "The name of the team",
                }
            },
            required: ["teamName"]
        }
    },
    {
        name: "list_tactics",
        description: "List all CS2 tactics available in the system.",
        parameters: {
            type: Type.OBJECT,
            properties: {}
        }
    },
    {
        name: "save_tactic",
        description: "Create and save a new CS2 tactic strategy document (Strat Sheet) to the system. Use this to output a completely new tactic to the user's tactic book. Ensure you use the document format (sections) instead of the legacy timeline format.",
        parameters: {
            type: Type.OBJECT,
            properties: {
                title: { type: Type.STRING, description: "Title of the tactic (e.g. 'Mirage A Execute')" },
                mapId: { type: Type.STRING, description: "Map ID (e.g. 'Mirage', 'Dust2', 'Inferno')" },
                side: { type: Type.STRING, description: "Side (e.g. 'Terrorist', 'Counter-Terrorist')" },
                type: { type: Type.STRING, description: "Type (e.g. 'Execute', 'Default', 'Pistol', 'Retake')" },
                sections: {
                    type: Type.ARRAY,
                    description: "The document sections (Strat Sheet blocks, e.g. 'Moves', 'Utility', 'AWP Moves')",
                    items: {
                        type: Type.OBJECT,
                        properties: {
                            title: { type: Type.STRING, description: "Section title (e.g. 'Utility Support')" },
                            content: { type: Type.STRING, description: "The content/details for this section (flexibly formatted text with details of the strategy)." }
                        },
                        required: ["title", "content"]
                    }
                },
                difficulty: { type: Type.STRING, description: "Difficulty level ('Easy', 'Medium', 'Hard')" }
            },
            required: ["title", "mapId", "side", "type", "sections"]
        }
    }
];

export const createToolHandlers = (context: any) => {
    return {
        get_team_stats: async ({ teamName }: { teamName: string }) => {
            return {
                result: `Not implemented. The team ${teamName} stats currently unavailable.`
            };
        },
        list_tactics: async () => {
            if (context.allTactics) {
                return { result: context.allTactics.map((t: any) => t.title || t.name) };
            }
            return { result: "No tactics found." };
        },
        save_tactic: async (args: any) => {
            if (context.onSaveTactic) {
                try {
                    const newTactic = {
                        id: 'tac-' + Date.now(),
                        title: args.title,
                        mapId: args.mapId || 'Mirage',
                        side: args.side || 'Terrorist',
                        type: args.type || 'Default',
                        site: 'Mid',
                        tags: [],
                        actions: [], // legacy empty
                        sections: args.sections?.map((s: any, i: number) => ({
                            id: `sec-${Date.now()}-${i}`,
                            title: s.title,
                            content: s.content
                        })) || [],
                        metadata: {
                            author: 'Copilot',
                            lastUpdated: new Date().toISOString(),
                            difficulty: args.difficulty || 'Medium'
                        }
                    };
                    context.onSaveTactic(newTactic, "Generated by Copilot");
                    return { result: `Tactic '${args.title}' has been successfully created and saved.` };
                } catch (e: any) {
                    return { result: `Failed to save tactic: ${e.message}` };
                }
            }
            return { result: "Error: onSaveTactic hook is not available." };
        }
    };
};
